import { createSlice } from "@reduxjs/toolkit"
const cartSlice = createSlice({
  name: "cart",
  initialState: {
    items: [
      {
        id: "1",
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        publisher: "Scribner",
        image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        description:
          "A novel about the American dream and the decadence of the 1920s.",
        rating: 4.2,
        category: "Fiction",
      },
      {
        id: "2",
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        publisher: "J.B. Lippincott & Co.",
        image: "https://covers.openlibrary.org/b/id/8225261-L.jpg",
        description:
          "A story of racial injustice and moral growth in the Deep South.",
        rating: 4.8,
        category: "Classic",
      },
      {
        id: "3",
        title: "1984",
        author: "George Orwell",
        publisher: "Secker & Warburg",
        image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        description:
          "A dystopian novel about totalitarianism and surveillance.",
        rating: 4.6,
        category: "Science Fiction",
      },
      {
        id: "4",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        publisher: "T. Egerton",
        image: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
        description: "A classic romance novel exploring manners and marriage.",
        rating: 4.7,
        category: "Romance",
      },
      {
        id: "5",
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        publisher: "George Allen & Unwin",
        image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
        description: "A fantasy adventure about Bilbo Baggins and a dragon.",
        rating: 4.9,
        category: "Fantasy",
      },
      {
        id: "6",
        title: "Moby Dick",
        author: "Herman Melville",
        publisher: "Harper & Brothers",
        image: "https://covers.openlibrary.org/b/id/8281999-L.jpg",
        description: "The epic tale of obsession and the sea.",
        rating: 4.3,
        category: "Adventure",
      },
      {
        id: "7",
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        publisher: "Little, Brown and Company",
        image: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
        description: "A story about teenage rebellion and alienation.",
        rating: 4.0,
        category: "Fiction",
      },
      {
        id: "8",
        title: "Brave New World",
        author: "Aldous Huxley",
        publisher: "Chatto & Windus",
        image: "https://covers.openlibrary.org/b/id/8231854-L.jpg",
        description: "A dystopian vision of a future society.",
        rating: 4.4,
        category: "Science Fiction",
      },
      {
        id: "9",
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        publisher: "The Russian Messenger",
        image: "https://covers.openlibrary.org/b/id/8231850-L.jpg",
        description: "A psychological novel about guilt and redemption.",
        rating: 4.5,
        category: "Philosophical",
      },
      {
        id: "10",
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        publisher: "George Allen & Unwin",
        image: "https://covers.openlibrary.org/b/id/8232094-L.jpg",
        description: "An epic fantasy adventure in Middle-earth.",
        rating: 4.9,
        category: "Fantasy",
      },
      {
        id: "11",
        title: "The Alchemist",
        author: "Paulo Coelho",
        publisher: "HarperOne",
        image: "https://covers.openlibrary.org/b/id/8232104-L.jpg",
        description: "A philosophical story about seeking one's destiny.",
        rating: 4.3,
        category: "Fiction",
      },
      {
        id: "12",
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        publisher: "Smith, Elder & Co.",
        image: "https://covers.openlibrary.org/b/id/8232101-L.jpg",
        description: "A novel about resilience and moral growth.",
        rating: 4.6,
        category: "Romance",
      },
      {
        id: "13",
        title: "The Odyssey",
        author: "Homer",
        publisher: "Penguin Classics",
        image: "https://covers.openlibrary.org/b/id/8232110-L.jpg",
        description: "Ancient Greek epic about Odysseus' adventures.",
        rating: 4.7,
        category: "Epic",
      },
      {
        id: "14",
        title: "Frankenstein",
        author: "Mary Shelley",
        publisher: "Lackington, Hughes, Harding, Mavor & Jones",
        image: "https://covers.openlibrary.org/b/id/8232099-L.jpg",
        description: "A gothic novel about creation and monstrosity.",
        rating: 4.2,
        category: "Gothic",
      },
      {
        id: "15",
        title: "War and Peace",
        author: "Leo Tolstoy",
        publisher: "The Russian Messenger",
        image: "https://covers.openlibrary.org/b/id/8232108-L.jpg",
        description:
          "A historical epic about Russia during the Napoleonic Wars.",
        rating: 4.4,
        category: "Historical",
      },
      {
        id: "16",
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        publisher: "Lippincott's Monthly Magazine",
        image: "https://covers.openlibrary.org/b/id/8232106-L.jpg",
        description: "A philosophical novel about vanity and corruption.",
        rating: 4.1,
        category: "Gothic",
      },
    ],
  },
  reducers: {
    addItem: (state, action) => {
      state.items.push(action.payload)
    },
  },
})
export const { addItem } = cartSlice.actions
export default cartSlice.reducer
