import { createSlice } from "@reduxjs/toolkit"
const cartSlice = createSlice({
  name: "cart",
  initialState: {
    items: [
      {
        id: "1",
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        publisher: "J.B. Lippincott & Co.",
        image: "https://covers.openlibrary.org/b/id/14856323-L.jpg",
        description:
          "A story of racial injustice and moral growth in the Deep South.",
        rating: 4.8,
        category: "Classic",
      },
      {
        id: "2",
        title: "1984",
        author: "George Orwell",
        publisher: "Secker & Warburg",
        image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        description:
          "A dystopian novel about totalitarianism and surveillance.",
        rating: 4.7,
        category: "Dystopian",
      },
      {
        id: "3",
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        publisher: "Charles Scribner's Sons",
        image: "https://covers.openlibrary.org/b/id/12364437-L.jpg",
        description:
          "A story of wealth, love, and the American Dream in the 1920s.",
        rating: 4.5,
        category: "Classic",
      },
      {
        id: "4",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        publisher: "T. Egerton, Whitehall",
        image: "https://covers.openlibrary.org/b/id/8090214-L.jpg",
        description:
          "A romantic novel about the Bennet family and their five daughters.",
        rating: 4.6,
        category: "Romance",
      },
      {
        id: "5",
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        publisher: "Little, Brown and Company",
        image: "https://covers.openlibrary.org/b/id/14845128-L.jpg",
        description: "A story about teenage rebellion and alienation.",
        rating: 4.0,
        category: "Coming-of-age",
      },
      {
        id: "6",
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        publisher: "George Allen & Unwin",
        image: "https://covers.openlibrary.org/b/id/14627222-L.jpg",
        description:
          "A fantasy novel about Bilbo Baggins' adventure to win a share of treasure.",
        rating: 4.8,
        category: "Fantasy",
      },
      {
        id: "7",
        title: "Fahrenheit 451",
        author: "Ray Bradbury",
        publisher: "Ballantine Books",
        image: "https://covers.openlibrary.org/b/id/14828158-L.jpg",
        description: "A dystopian novel about book burning and censorship.",
        rating: 4.3,
        category: "Dystopian",
      },
      {
        id: "8",
        title: "Moby-Dick",
        author: "Herman Melville",
        publisher: "Harper & Brothers",
        image: "https://covers.openlibrary.org/b/id/12621992-L.jpg",
        description:
          "The voyage of the whaling ship Pequod and its captain Ahab.",
        rating: 4.1,
        category: "Adventure",
      },
      {
        id: "9",
        title: "War and Peace",
        author: "Leo Tolstoy",
        publisher: "The Russian Messenger",
        image: "https://covers.openlibrary.org/b/id/7914757-L.jpg",
        description: "A historical novel about French invasion of Russia.",
        rating: 4.2,
        category: "Historical",
      },
      {
        id: "10",
        title: "The Odyssey",
        author: "Homer",
        publisher: "Various",
        image: "https://covers.openlibrary.org/b/id/14502423-L.jpg",
        description:
          "An epic poem about Odysseus's journey home after the Trojan War.",
        rating: 4.4,
        category: "Epic",
      },
      {
        id: "11",
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        publisher: "The Russian Messenger",
        image: "https://covers.openlibrary.org/b/id/14911181-L.jpg",
        description:
          "A psychological novel about a poor ex-student's murder of a pawnbroker.",
        rating: 4.5,
        category: "Psychological",
      },
      {
        id: "12",
        title: "The Alchemist",
        author: "Paulo Coelho",
        publisher: "HarperTorch",
        image: "https://covers.openlibrary.org/b/id/15102369-L.jpg",
        description:
          "A philosophical book about a shepherd's journey to find treasure.",
        rating: 4.6,
        category: "Philosophical",
      },
      {
        id: "13",
        title: "Brave New World",
        author: "Aldous Huxley",
        publisher: "Chatto & Windus",
        image: "https://covers.openlibrary.org/b/id/14846947-L.jpg",
        description: "A dystopian novel about a futuristic World State.",
        rating: 4.2,
        category: "Dystopian",
      },
      {
        id: "14",
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        publisher: "George Allen & Unwin",
        image: "https://covers.openlibrary.org/b/id/14627570-L.jpg",
        description: "An epic fantasy about the quest to destroy the One Ring.",
        rating: 4.9,
        category: "Fantasy",
      },
      {
        id: "15",
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        publisher: "Smith, Elder & Co.",
        image: "https://covers.openlibrary.org/b/id/12752089-L.jpg",
        description:
          "A novel about an orphan's growth to adulthood and love for Mr. Rochester.",
        rating: 4.4,
        category: "Gothic",
      },
      {
        id: "16",
        title: "Animal Farm",
        author: "George Orwell",
        publisher: "Secker & Warburg",
        image: "https://covers.openlibrary.org/b/id/11261770-L.jpg",
        description:
          "An allegorical novella about farm animals rebelling against humans.",
        rating: 4.3,
        category: "Political",
      },
      {
        id: "17",
        title: "Wuthering Heights",
        author: "Emily Brontë",
        publisher: "Thomas Cautley Newby",
        image: "https://covers.openlibrary.org/b/id/12775461-L.jpg",
        description: "A story of love and revenge on the Yorkshire moors.",
        rating: 4.1,
        category: "Gothic",
      },
      {
        id: "18",
        title: "The Grapes of Wrath",
        author: "John Steinbeck",
        publisher: "The Viking Press",
        image: "https://covers.openlibrary.org/b/id/14424110-L.jpg",
        description:
          "A novel about the Great Depression and Dust Bowl migration.",
        rating: 4.3,
        category: "Historical",
      },
      {
        id: "19",
        title: "The Brothers Karamazov",
        author: "Fyodor Dostoevsky",
        publisher: "The Russian Messenger",
        image: "https://covers.openlibrary.org/b/id/8272329-L.jpg",
        description: "A philosophical novel about faith, doubt, and morality.",
        rating: 4.4,
        category: "Philosophical",
      },
      {
        id: "20",
        title: "Don Quixote",
        author: "Miguel de Cervantes",
        publisher: "Francisco de Robles",
        image: "https://covers.openlibrary.org/b/id/5697757-L.jpg",
        description:
          "The adventures of a noble who reads too many chivalric romances.",
        rating: 4.2,
        category: "Satire",
      },
      {
        id: "21",
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        publisher: "Ward, Lock and Company",
        image: "https://covers.openlibrary.org/b/id/12752033-L.jpg",
        description: "A philosophical novel about beauty, youth, and morality.",
        rating: 4.3,
        category: "Gothic",
      },
      {
        id: "22",
        title: "Frankenstein",
        author: "Mary Shelley",
        publisher: "Lackington, Hughes, Harding, Mavor & Jones",
        image: "https://covers.openlibrary.org/b/id/12752093-L.jpg",
        description:
          "A Gothic novel about a scientist who creates a sapient creature.",
        rating: 4.2,
        category: "Horror",
      },
      {
        id: "23",
        title: "The Divine Comedy",
        author: "Dante Alighieri",
        publisher: "Various",
        image: "https://covers.openlibrary.org/b/id/6128356-L.jpg",
        description:
          "An epic poem about the journey through Hell, Purgatory, and Heaven.",
        rating: 4.5,
        category: "Epic",
      },
      {
        id: "24",
        title: "One Hundred Years of Solitude",
        author: "Gabriel García Márquez",
        publisher: "Harper & Row",
        image: "https://covers.openlibrary.org/b/id/10454740-L.jpg",
        description: "A multi-generational story of the Buendía family.",
        rating: 4.6,
        category: "Magical Realism",
      },
      {
        id: "25",
        title: "The Adventures of Huckleberry Finn",
        author: "Mark Twain",
        publisher: "Chatto & Windus",
        image: "https://covers.openlibrary.org/b/id/8458117-L.jpg",
        description:
          "A novel about a boy's journey down the Mississippi River.",
        rating: 4.3,
        category: "Adventure",
      },
      {
        id: "26",
        title: "The Count of Monte Cristo",
        author: "Alexandre Dumas",
        publisher: "Pétion",
        image: "https://covers.openlibrary.org/b/id/14564033-L.jpg",
        description: "A tale of betrayal, revenge, and redemption.",
        rating: 4.7,
        category: "Adventure",
      },
      {
        id: "27",
        title: "Anna Karenina",
        author: "Leo Tolstoy",
        publisher: "The Russian Messenger",
        image: "https://covers.openlibrary.org/b/id/10598462-L.jpg",
        description: "A tragic novel about an aristocratic woman's affair.",
        rating: 4.5,
        category: "Tragedy",
      },
      {
        id: "28",
        title: "The Stranger",
        author: "Albert Camus",
        publisher: "Éditions Gallimard",
        image: "https://covers.openlibrary.org/b/id/14891008-L.jpg",
        description: "A philosophical novel about absurdism and detachment.",
        rating: 4.1,
        category: "Philosophical",
      },
      {
        id: "29",
        title: "Slaughterhouse-Five",
        author: "Kurt Vonnegut",
        publisher: "Delacorte Press",
        image: "https://covers.openlibrary.org/b/id/12919155-L.jpg",
        description: "A satirical novel about World War II and time travel.",
        rating: 4.3,
        category: "Satire",
      },
      {
        id: "30",
        title: "The Little Prince",
        author: "Antoine de Saint-Exupéry",
        publisher: "Reynal & Hitchcock",
        image: "https://covers.openlibrary.org/b/id/14994367-L.jpg",
        description: "A poetic tale about a prince who visits various planets.",
        rating: 4.8,
        category: "Children's",
      },
    ],
  },
  reducers: {
    addItem: (state, action) => {
      state.items.push(action.payload)
    },
  },
})

// const Books = [
//       {
//         id: "1",
//         title: "The Great Gatsby",
//         author: "F. Scott Fitzgerald",
//         publisher: "Scribner",
//         image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
//         description:
//           "A novel about the American dream and the decadence of the 1920s.",
//         rating: 4.2,
//         category: "Fiction",
//       },
//       {
//         id: "2",
//         title: "To Kill a Mockingbird",
//         author: "Harper Lee",
//         publisher: "J.B. Lippincott & Co.",
//         image: "https://covers.openlibrary.org/b/id/8225261-L.jpg",
//         description:
//           "A story of racial injustice and moral growth in the Deep South.",
//         rating: 4.8,
//         category: "Classic",
//       },
//       {
//         id: "3",
//         title: "1984",
//         author: "George Orwell",
//         publisher: "Secker & Warburg",
//         image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
//         description:
//           "A dystopian novel about totalitarianism and surveillance.",
//         rating: 4.6,
//         category: "Science Fiction",
//       },
//       {
//         id: "4",
//         title: "Pride and Prejudice",
//         author: "Jane Austen",
//         publisher: "T. Egerton",
//         image: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
//         description: "A classic romance novel exploring manners and marriage.",
//         rating: 4.7,
//         category: "Romance",
//       },
//       {
//         id: "5",
//         title: "The Hobbit",
//         author: "J.R.R. Tolkien",
//         publisher: "George Allen & Unwin",
//         image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
//         description: "A fantasy adventure about Bilbo Baggins and a dragon.",
//         rating: 4.9,
//         category: "Fantasy",
//       },
//       {
//         id: "6",
//         title: "Moby Dick",
//         author: "Herman Melville",
//         publisher: "Harper & Brothers",
//         image: "https://covers.openlibrary.org/b/id/8281999-L.jpg",
//         description: "The epic tale of obsession and the sea.",
//         rating: 4.3,
//         category: "Adventure",
//       },
//       {
//         id: "7",
//         title: "The Catcher in the Rye",
//         author: "J.D. Salinger",
//         publisher: "Little, Brown and Company",
//         image: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
//         description: "A story about teenage rebellion and alienation.",
//         rating: 4.0,
//         category: "Fiction",
//       },
//       {
//         id: "8",
//         title: "Brave New World",
//         author: "Aldous Huxley",
//         publisher: "Chatto & Windus",
//         image: "https://covers.openlibrary.org/b/id/8231854-L.jpg",
//         description: "A dystopian vision of a future society.",
//         rating: 4.4,
//         category: "Science Fiction",
//       },
//       {
//         id: "9",
//         title: "Crime and Punishment",
//         author: "Fyodor Dostoevsky",
//         publisher: "The Russian Messenger",
//         image: "https://covers.openlibrary.org/b/id/8231850-L.jpg",
//         description: "A psychological novel about guilt and redemption.",
//         rating: 4.5,
//         category: "Philosophical",
//       },
//       {
//         id: "10",
//         title: "The Lord of the Rings",
//         author: "J.R.R. Tolkien",
//         publisher: "George Allen & Unwin",
//         image: "https://covers.openlibrary.org/b/id/8232094-L.jpg",
//         description: "An epic fantasy adventure in Middle-earth.",
//         rating: 4.9,
//         category: "Fantasy",
//       },
//       {
//         id: "11",
//         title: "The Alchemist",
//         author: "Paulo Coelho",
//         publisher: "HarperOne",
//         image: "https://covers.openlibrary.org/b/id/8232104-L.jpg",
//         description: "A philosophical story about seeking one's destiny.",
//         rating: 4.3,
//         category: "Fiction",
//       },
//       {
//         id: "12",
//         title: "Jane Eyre",
//         author: "Charlotte Brontë",
//         publisher: "Smith, Elder & Co.",
//         image: "https://covers.openlibrary.org/b/id/8232101-L.jpg",
//         description: "A novel about resilience and moral growth.",
//         rating: 4.6,
//         category: "Romance",
//       },
//       {
//         id: "13",
//         title: "The Odyssey",
//         author: "Homer",
//         publisher: "Penguin Classics",
//         image: "https://covers.openlibrary.org/b/id/8232110-L.jpg",
//         description: "Ancient Greek epic about Odysseus' adventures.",
//         rating: 4.7,
//         category: "Epic",
//       },
//       {
//         id: "14",
//         title: "Frankenstein",
//         author: "Mary Shelley",
//         publisher: "Lackington, Hughes, Harding, Mavor & Jones",
//         image: "https://covers.openlibrary.org/b/id/8232099-L.jpg",
//         description: "A gothic novel about creation and monstrosity.",
//         rating: 4.2,
//         category: "Gothic",
//       },
//       {
//         id: "15",
//         title: "War and Peace",
//         author: "Leo Tolstoy",
//         publisher: "The Russian Messenger",
//         image: "https://covers.openlibrary.org/b/id/8232108-L.jpg",
//         description:
//           "A historical epic about Russia during the Napoleonic Wars.",
//         rating: 4.4,
//         category: "Historical",
//       },
//       {
//         id: "16",
//         title: "The Picture of Dorian Gray",
//         author: "Oscar Wilde",
//         publisher: "Lippincott's Monthly Magazine",
//         image: "https://covers.openlibrary.org/b/id/8232106-L.jpg",
//         description: "A philosophical novel about vanity and corruption.",
//         rating: 4.1,
//         category: "Gothic",
//       },
//     ],
export const { addItem } = cartSlice.actions
export default cartSlice.reducer
